# Generated by Django 5.2 on 2025-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('piano', 'Piano'), ('violin', 'Violin'), ('flute', 'Flute'), ('drums', 'Drums'), ('other', 'Other')], max_length=100)),
                ('duration', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
